feat: elb & certs for seed addresses
dashpay/dash-network-deploy pull request #504
Opened 2023-05-16 19:04 UTC by ktechmidas

## Issue being fixed or feature implemented
The feature here is the creation and configuration of an AWS Elastic Load Balancer (ELB), ACM Certificate, Route53 Record and Security Group using Terraform. This setup is required to make seed-*.testnet.networks.dash.org accessible over HTTPS since the old method will not work while DAPI has differing certificates.

## What was done?
New ELB for seeds with the correct certificates, adding HPMNs as backends on port 3001. 

## How Has This Been Tested?
devnet-dude

## Breaking Changes
N/A

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-05-17 00:23 UTC, shumkov submitted a review, later dismissed

2023-05-17 00:23 UTC, shumkov commented on terraform/aws/main.tf
> +  port              = 443
It should be dapi_port variable

2023-05-17 00:23 UTC, shumkov commented on terraform/aws/main.tf
> +  port     = 3001
It should be dapi_port as well

2023-05-17 00:23 UTC, shumkov commented on terraform/aws/security_groups.tf
> +    from_port   = 443
dapi_port?

2023-05-17 01:32 UTC, strophy requested changes
Nice work, general design looks good. Left a few code comments. Would a network load balancer be sufficient here, why do we need the ALB?

2023-05-17 01:32 UTC, strophy commented on terraform/aws/main.tf
> +resource "aws_lb" "seed-elb" {
Snake case for variable names instead of kebab case

2023-05-17 01:32 UTC, strophy commented on terraform/aws/security_groups.tf
> +resource "aws_security_group" "sg-seed" {
Other security groups are not named with `sg-` prefix, follow naming convention

2023-05-17 01:32 UTC, strophy commented on terraform/aws/main.tf
> -  count = length(var.main_domain) > 1 ? 5 : 0
Can we keep this method of iteration? The new code is less flexible in the number of R53 records created.

2023-05-17 02:07 UTC, ktechmidas commented
@strophy could have gone either way, but if DAPI could, for example, tell us if a node is banned it could be removed, A/B testing could be done etc

An ALB is only a tiny bit more expensive and gives us more options

plus:

> Both Classic Load Balancers and Application Load Balancers use connection multiplexing, but Network Load Balancers do not. Therefore, your targets can receive more TCP connections behind a Network Load Balancer. Be sure that your targets are prepared to handle the volume of connection requests they might receive.

2023-05-17 07:29 UTC, strophy commented on terraform/aws/security_groups.tf
> +  }
What is this for?

2023-05-17 07:30 UTC, strophy commented on terraform/aws/security_groups.tf
> +    description = "TLS from VPC"
Isn't this from everywhere?

2023-05-18 01:44 UTC, strophy approved these changes
Nice work mate!

2023-05-18 01:46 UTC, merged