feat: add Elasticsearch, Metricbeat, and Kibana Ansible roles
dashpay/dash-network-deploy pull request #625
Opened 2024-03-11 16:36 UTC by vivekgsharma

## Issue being fixed or feature implemented
This change adds initial support for Elasticsearch, Metricbeat, and Kibana through new Ansible roles. It's part of setting up monitoring and visualization for the Dash network deployment tool.

## What was done?
- Added Ansible roles for Elasticsearch, Metricbeat, and Kibana.
- Updated the `deploy.yml` file to invoke these roles.
- Placeholder entries have been added for the target hosts for these services, to be defined later.
- Note: Terraform resources for these services are not included in this PR and will be defined in subsequent updates.

## How Has This Been Tested?

## Breaking Changes
- None: This is an additive change and does not alter existing infrastructure or workflows.

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-03-12 00:03 UTC, ktechmidas commented on ansible/roles/elasticsearch/tasks/main.yml
We already have the elastic_stack role

2024-03-13 12:22 UTC, shumkov commented on ansible/roles/metricbeat/tasks/main.yml
> +---
How this is better than using already existing role?

2024-03-13 12:22 UTC, shumkov requested changes

2024-03-13 12:22 UTC, shumkov commented on ansible/roles/metricbeat/tasks/main.yml
> +    dest: "/etc/metricbeat/modules.d/{{ item | basename }}"
Are there any modules or module configuration is provided?

2024-03-14 08:56 UTC, lklimek commented
Let me redefine the task.

### Current state

1. We already start an elastic cluster that is available at addresses like http://logs.testnet.networks.dash.org:5601/login?next=%2F
2. We have a prometheus server deployed for devnets which contains services: prometheus, grafana
3. Some initial work was done by Ivan to enable metricbeat in #617 
4. Right now, prometheus config is generated with Ansible (mainly list of addresses to collect metrics from)

### Long-term goal (epic)

1. Migrate Grafana to elastic cluster nodes.
2. Automate configuration of Grafana.
3. Replace promethus with metricbeat (read data from prometheus exporters into metricbeat)

### This task

Goal of this task is to replace prometheus with metricbeat.

To achieve this, we need to:

* get familiar with existing Ansible code 
* extend existing code by enabling and configuring [metricbeat prometheus collector](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-prometheus-collector.html)
* configure metricbeat prometheus collector to reach each Tenderdash Prometheus exporter in the devnet

### Acceptance criteria

* Each Tenderdash node reports metrics to Elastic stack, for example, metric ending with `_consensus_height` exists in elastic for every hpmn
* Grafana can visualize these metrics
* Existing ansible code is modified whenever possible

2024-03-15 13:36 UTC, closed without merging