feat: dynamic update of yml
dashpay/dash-network-deploy pull request #626
Opened 2024-03-12 01:34 UTC by ktechmidas

## Issue being fixed or feature implemented
We've moved the load test/mixer/metrics nodes out of the generate file. We need a way to dynamically update the yml file when we change tfvars

## What was done?
Created a "bridge" in node which will dynamically update the yml file

## How Has This Been Tested?
On tfvars and yml files.

## Breaking Changes
None

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-03-12 01:34 UTC, ktechmidas commented
@shumkov this is not ready for review yet, but I would love your input

2024-03-18 08:31 UTC, ktechmidas commented
@shumkov this can be extended to masternodes/hp-masternodes later, for now I'd like to put into feat/load-test as is so we can merge that branch into 1.0

2024-03-20 11:33 UTC, shumkov requested changes

2024-03-20 11:33 UTC, shumkov commented on bin/firstRun.js
> +    console.log(network);
I guess it's a debug output

2024-03-20 15:31 UTC, shumkov approved these changes

2024-03-20 15:59 UTC, merged